[workspace]
members = [
    "axum-liveview",
    "demo-app",
]

[patch.crates-io]
tokio = { git = "https://github.com/tokio-rs/tokio.git" }
tokio-stream = { git = "https://github.com/tokio-rs/tokio.git" }
